// Code generated by traust-contracts codegen. DO NOT EDIT.

package enums

// SourceType — Event source type classifying evidence origin. Evidence classes for validity precedence: validation_report/verification_report/fuzz_report are execution-verified (class 1), human static (class 2), machine static incl. triage_report/impact_report/vuln_scan_report (class 3). rebaseline is NOT an evidence class and never participates in validity precedence: it records that a finding was RENAMED, so the alias lives in the Merkle-covered event stream rather than in mutable metadata.Every one of them carries an EMPTY disposition, which is the invariant a consumer should rely on -- a rebaseline event asserts nothing about whether a finding is real.
type SourceType string

const (
	SourceTypeMrComment          SourceType = "mr_comment"
	SourceTypeCommit             SourceType = "commit"
	SourceTypeJira               SourceType = "jira"
	SourceTypeInteractive        SourceType = "interactive"
	SourceTypeValidationReport   SourceType = "validation_report"
	SourceTypeVerificationReport SourceType = "verification_report"
	SourceTypeTriageReport       SourceType = "triage_report"
	SourceTypeImpactReport       SourceType = "impact_report"
	SourceTypeVulnScanReport     SourceType = "vuln_scan_report"
	SourceTypeFuzzReport         SourceType = "fuzz_report"
	SourceTypeRebaseline         SourceType = "rebaseline"
)

// SourceTypeValues returns all valid SourceType values.
func SourceTypeValues() []SourceType {
	return []SourceType{
		SourceTypeMrComment,
		SourceTypeCommit,
		SourceTypeJira,
		SourceTypeInteractive,
		SourceTypeValidationReport,
		SourceTypeVerificationReport,
		SourceTypeTriageReport,
		SourceTypeImpactReport,
		SourceTypeVulnScanReport,
		SourceTypeFuzzReport,
		SourceTypeRebaseline,
	}
}
